name: Check code quality
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run oxlint
        if: ${{ !cancelled() }}
        run: pnpm exec oxlint .
      # *.astro files not formatted until Astro support (oxc#19715)
      - name: Run oxfmt
        if: ${{ !cancelled() }}
        run: pnpm exec oxfmt --check .
  test:
    name: Test by building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test building
        if: ${{ !cancelled() }}
        run: pnpm run build
